eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery1.local:8761/eureka,http://discovery2.local:8762/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
spring:
  datasource:
    initialize: false
    password: '{cipher}15305f3a64f6ba6e443728eed55b39c335ef9cf4563b07423b5cce5bc880df11'
    url: jdbc:mysql://localhost:3306/pocArchi?useSSL=false
    username: root
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    openInView: false
    show_sql: true
  profiles: development
